
// {"application":{"appPermissionrequested":["android.permission.ACCESS_NETWORK_STATE","android.permission.CAMERA","android.permission.RECORD_AUDIO","android.permission.NFC",
// "android.permission.INTERNET","android.permission.HIGH_SAMPLING_RATE_SENSORS","android.permission.WAKE_LOCK","android.permission.ACCESS_WIFI_STATE"],
// "appPermissionsGranted":["android.permission.ACCESS_NETWORK_STATE","android.permission.CAMERA","android.permission.RECORD_AUDIO","android.permission.NFC",
// "android.permission.INTERNET","android.permission.HIGH_SAMPLING_RATE_SENSORS","android.permission.WAKE_LOCK","android.permission.ACCESS_WIFI_STATE"],
// "appVersionCode":2,"appVersionName":"1.0.1","isAdbOpen":false,"isDebug":false,"packageName":"com.castles.softpos.client","transactionInitiationVolume":0,
// "transactionSuccessVolume":0,"transactionFailureVolume":0,"instanceID":"e4RAPX8oSE-RaDmMTIMeDI","ctEmvCl":"v9.0.010701-20230511-00000001","kms":"v1.1.2-de1",
// "ctPay":"CTPAY.CtSoftPos_0.0.01","csp":"1.0.0.20230512-00000001","csi":"1.0.0","isKeyInSecureHardware":true},"device_id":"7576aa67c1cf61fd",
// "platform":{"NFCDetail":{"NFCApps":[{"appName":"Google Play ååº","packageName":"com.android.vending"},{"appName":"NFCæå¡","packageName":"com.android.nfc"},
// {"appName":"Google Play æå¡","packageName":"com.google.android.gms"},{"appName":"Retail Demo Mode","packageName":"com.customermobile.preload.vzw"},
// {"appName":"å·¥ä½è®¾ç½®","packageName":"com.android.managedprovisioning"},{"appName":"è®¾ç½®","packageName":"com.android.settings"},
// {"appName":"Shell","packageName":"com.android.shell"},{"appName":"PaymentDemo","packageName":"com.castles.softpos.client"}],"NFCEnable":true,"NFCStatus":true},
// "SDK_INT":"32","androidID":"7576aa67c1cf61fd","appList":[{"appName":"Tethering","packageName":"com.google.android.networkstack.tethering",
// "versionCode":33,"versionName":"13-9467362"},{"appName":"OemDmTrigger","packageName":"com.google.omadm.trigger","versionCode":1,"versionName":"1.0"},
// {"appName":"Carrier Setup","packageName":"com.google.android.carriersetup","versionCode":32,"versionName":"12"},{"appName":"Android Services Library",
// "packageName":"com.google.android.ext.services","versionCode":331412000,"versionName":"aml_ext_331412000"},
// {"appName":"çµè¯åç­ä¿¡å­å¨","packageName":"com.android.providers.telephony","versionCode":32,"versionName":"12"},
// {"appName":"Dynamic System Updates","packageName":"com.android.dynsystem","versionCode":32,"versionName":"12"},
// {"appName":"ConnMO","packageName":"com.android.sdm.plugins.connmo","versionCode":1,"versionName":"1.0"},
// {"appName":"Cell Broadcast Service","packageName":"com.google.android.cellbroadcastservice",
// "versionCode":300000000,"versionName":"R-initial"},{"appName":"æ¥åå­å¨",
// "packageName":"com.android.providers.calendar","versionCode":32,"versionName":"12"},{"appName":"com.android.providers.media",
// "packageName":"com.android.providers.media","versionCode":1024,"versionName":"12"},
// {"appName":"com.android.hbmsvmanager","packageName":"com.android.hbmsvmanager","versionCode":2,"versionName":"1.0"},
// {"appName":"è¶çº§ççµæ¨¡å¼","packageName":"com.google.android.flipendo","versionCode":32,"versionName":"12"},
// {"appName":"å¤é¨å­å¨è®¾å¤","packageName":"com.android.externalstorage","versionCode":32,"versionName":"12"},
// {"appName":"éå¥è®¾å¤ç®¡çå¨","packageName":"com.android.companiondevicemanager","versionCode":32,"versionName":"12"},
// {"appName":"MmsService","packageName":"com.android.mms.service","versionCode":32,"versionName":"12"},
// {"appName":"åå®¹ä¸è½½ç®¡çå¨","packageName":"com.android.providers.downloads","versionCode":32,"versionName":"12"},
// {"appName":"USCC","packageName":"com.android.sdm.plugins.usccdm","versionCode":1,"versionName":"1.0"},
// {"appName":"åªä½","packageName":"com.google.android.providers.media.module","versionCode":33,"versionName":"13-9427200"},
// {"appName":"com.google.android.overlay.udfpsoverlay","packageName":"com.google.android.overlay.udfpsoverlay","versionCode":1,"versionName":"1.0"},
// {"appName":"com.google.android.wifi.resources.pixel","packageName":"com.google.android.wifi.resources.pixel","versionCode":1,"versionName":"1.0"},
// {"appName":"Factory OTA Mode","packageName":"com.google.android.factoryota","versionCode":11000133,"versionName":"1.0.417357988"},
// {"appName":"com.android.systemui.plugin.globalactions.wallet","packageName":"com.android.systemui.plugin.globalactions.wallet","versionCode":10000000,"versionName":"1.0.0.0"},
// {"appName":"ä¸è½½","packageName":"com.android.providers.downloads.ui","versionCode":32,"versionName":"12"},
// {"appName":"Google Play ååº","packageName":"com.android.vending","versionCode":83471010,"versionName":"34.7.10-21 [0] [PR] 512129822"},
// {"appName":"PacProcessor","packageName":"com.android.pacprocessor","versionCode":32,"versionName":"12"},
// {"appName":"è¯ä¹¦å®è£ç¨åº","packageName":"com.android.certinstaller","versionCode":32,"versionName":"12"},
// {"appName":"Android ç³»ç»","packageName":"android","versionCode":32,"versionName":"12"},
// {"appName":"Android S Easter Egg","packageName":"com.android.egg","versionCode":12,"versionName":"1.0"},
// {"appName":"MTP ä¸»æº","packageName":"com.android.mtp","versionCode":32,"versionName":"12"},
// {"appName":"NFCæå¡","packageName":"com.android.nfc","versionCode":32,"versionName":"12"},
// {"appName":"com.android.ons","packageName":"com.android.ons","versionCode":32,"versionName":"12"},
// {"appName":"SIM å¡å·¥å·å","packageName":"com.android.stk","versionCode":32,"versionName":"12"},
// {"appName":"com.android.backupconfirm","packageName":"com.android.backupconfirm","versionCode":32,"versionName":"12"},
// {"appName":"RadioConfigService","packageName":"com.samsung.slsi.telephony.oem.oemrilhookservice","versionCode":1,"versionName":"1.0"},
// {"appName":"Intent Filter Verification Service","packageName":"com.android.statementservice","versionCode":1,"versionName":"1.0"},
// {"appName":"Device Health Services Adapter","packageName":"com.google.android.turboadapter","versionCode":32,"versionName":"12"},
// {"appName":"æéæ§å¶å¨","packageName":"com.google.android.permissioncontroller","versionCode":331411000,"versionName":"aml_per_331411000"},
// {"appName":"è®¾ç½®å­å¨","packageName":"com.android.providers.settings","versionCode":32,"versionName":"12"},
// {"appName":"com.android.sharedstoragebackup","packageName":"com.android.sharedstoragebackup","versionCode":32,"versionName":"12"},
// {"appName":"com.google.android.iwlan","packageName":"com.google.android.iwlan","versionCode":32,"versionName":"12"},
// {"appName":"com.android.sdm.plugins.diagmon","packageName":"com.android.sdm.plugins.diagmon","versionCode":32,"versionName":"12"},
// {"appName":"SecureElementApplication","packageName":"com.android.se","versionCode":32,"versionName":"12"},
// {"appName":"è¾å¥è®¾å¤","packageName":"com.android.inputdevices","versionCode":32,"versionName":"12"},
// {"appName":"æ°å­å¥åº·","packageName":"com.google.android.apps.wellbeing","versionCode":329097,"versionName":"1.0.410515141 (329097)"},
// {"appName":"com.android.cellbroadcastreceiver","packageName":"com.android.cellbroadcastreceiver","versionCode":300000000,"versionName":"R-initial"},
// {"appName":"ç½ç»ç®¡çå¨","packageName":"com.google.android.networkstack","versionCode":331412000,"versionName":"aml_net_331412000"},
// {"appName":"çµè¯","packageName":"com.android.server.telecom","versionCode":32,"versionName":"12"},
// {"appName":"å¯é¥é¾","packageName":"com.android.keychain","versionCode":32,"versionName":"12"},
// {"appName":"è½¯ä»¶åå®è£ç¨åº","packageName":"com.google.android.packageinstaller","versionCode":32,"versionName":"12"},
// {"appName":"Google Play æå¡","packageName":"com.google.android.gms","versionCode":230815044,"versionName":"23.08.15 (190400-512743456)"},
// {"appName":"Google æå¡æ¡æ¶","packageName":"com.google.android.gsf","versionCode":32,"versionName":"12"},
// {"appName":"Google è¯­é³æå¡","packageName":"com.google.android.tts","versionCode":210414469,"versionName":"googletts.google-speech-apk_20230206.01_p2.509666633"},
// {"appName":"Call Log Backup\/Restore","packageName":"com.android.calllogbackup","versionCode":32,"versionName":"12"},
// {"appName":"CameraExtensionsProxy","packageName":"com.android.cameraextensions","versionCode":32,"versionName":"12"},
// {"appName":"com.android.localtransport","packageName":"com.android.localtransport","versionCode":32,"versionName":"12"},
// {"appName":"com.google.euiccpixel.overlay.gs101","packageName":"com.google.euiccpixel.overlay.gs101","versionCode":1,"versionName":"1.0"},
// {"appName":"è¿è¥åé»è®¤åºç¨","packageName":"com.android.carrierdefaultapp","versionCode":32,"versionName":"12"},
// {"appName":"RilConfig","packageName":"com.google.RilConfigService","versionCode":32,"versionName":"12"},
// {"appName":"ProxyHandler","packageName":"com.android.proxyhandler","versionCode":32,"versionName":"12"},
// {"appName":"com.google.SSRestartDetector","packageName":"com.google.SSRestartDetector","versionCode":32,"versionName":"12"},
// {"appName":"Retail Demo Mode","packageName":"com.customermobile.preload.vzw","versionCode":22,"versionName":"Retail Demo Mode"},
// {"appName":"å·¥ä½è®¾ç½®","packageName":"com.android.managedprovisioning","versionCode":32,"versionName":"12"},
// {"appName":"å£°é³","packageName":"com.android.soundpicker","versionCode":32,"versionName":"12"},
// {"appName":"SystemUIGX","packageName":"com.google.android.systemui.gxoverlay","versionCode":32,"versionName":"12"},
// {"appName":"Carrier OMADM","packageName":"com.android.sdm.plugins.dcmo","versionCode":32,"versionName":"12"},
// {"appName":"Pixel ç¸æºæå¡","packageName":"com.google.android.apps.camera.services","versionCode":124657,"versionName":"1.0.491427692.03"},
// {"appName":"Live Wallpaper Picker","packageName":"com.android.wallpaper.livepicker","versionCode":32,"versionName":"12"},
// {"appName":"com.google.android.apps.cbrsnetworkmonitor","packageName":"com.google.android.apps.cbrsnetworkmonitor","versionCode":6,"versionName":"6.1.407437803"},
// {"appName":"com.android.server.NetworkPermissionConfig","packageName":"com.google.android.networkstack.permissionconfig","versionCode":300000000,"versionName":"2019-09"},
// {"appName":"è®¾ç½®","packageName":"com.android.settings","versionCode":32,"versionName":"12"},
// {"appName":"è®¾å¤ç®¡çæå¡","packageName":"com.android.omadm.service","versionCode":1,"versionName":"1.0.0"},
// {"appName":"Connectivity Thermal Power Manager","packageName":"com.google.android.connectivitythermalpowermanager","versionCode":32,"versionName":"12"},
// {"appName":"VpnDialogs","packageName":"com.android.vpndialogs","versionCode":32,"versionName":"12"},
// {"appName":"com.android.angle","packageName":"com.android.angle","versionCode":32,"versionName":"12"},
// {"appName":"çµè¯æå¡","packageName":"com.android.phone","versionCode":32,"versionName":"12"},
// {"appName":"Shell","packageName":"com.android.shell","versionCode":32,"versionName":"12"},
// {"appName":"PaymentDemo","packageName":"com.castles.softpos.client","versionCode":2,"versionName":"1.0.1"},
// {"appName":"com.android.wallpaperbackup","packageName":"com.android.wallpaperbackup","versionCode":32,"versionName":"12"},
// {"appName":"å­å¨å·²å±è½çå·ç ","packageName":"com.android.providers.blockednumber","versionCode":32,"versionName":"12"},
// {"appName":"ç¨æ·å­å¸","packageName":"com.android.providers.userdictionary","versionCode":32,"versionName":"12"},
// {"appName":"Emergency information","packageName":"com.android.emergency","versionCode":32,"versionName":"12"},
// {"appName":"ä¸ä½åä½ç½®ä¿¡æ¯","packageName":"com.android.location.fused","versionCode":32,"versionName":"12"},
// {"appName":"ç³»ç»çé¢","packageName":"com.android.systemui","versionCode":32,"versionName":"12"},
// {"appName":"èç","packageName":"com.android.bluetooth","versionCode":32,"versionName":"12"},
// {"appName":"èç³»äººå­å¨","packageName":"com.android.providers.contacts","versionCode":32,"versionName":"12"},
// {"appName":"com.verizon.llkagent","packageName":"com.verizon.llkagent","versionCode":32,"versionName":"12"}],
// "buildInfo":{"CurCpuFreq":"1803000","MaxCpuFreq":"1803000","MinCpuFreq":"300000","availableMemory":"2449870848","availableRomSpace":"108794150912","base_OS":"",
// "board":"bluejay","bootloader":"bluejay-1.1-8419703","brand":"google",
// "codeNAME":"REL","display":"SD2A.220601.003.B1","fingerprint":"google\/bluejay\/bluejay:12\/SD2A.220601.003.B1\/8836721:user\/release-keys",
// "incremental":"8836721","manufacturer":"Google","model":"Pixel 6a","product":"bluejay","radio":"unknown","release":"12",
// "scaling_available_frequencies":"300000 574000 738000 930000 1098000 1197000 1328000 1401000 1598000 1704000 1803000 ",
// "scaling_available_governors":"sched_pixel conservative powersave performance schedutil ","totalMemory":"5851979776","totalRomSpace":"128000000000"},
// "emulatorStatus":{"hasGenyFiles":false,"hasKnownPhoneNumber":false,"hasPipes":false,"hasQEmuFiles":false,"hasqemuDrivers":false,"isOperatorNameAndroid":false},
// "googlePlayServiceVersion":"23.08.15 (190400-512743456)","hasCameraPermission":true,"hasLigntSensor":true,"hasMicroPhonePermission":true,"hookStatus":false,
// "isGooglePlayServiceAvailable":true,"macAddress":"","rootStatus":{"ForRWPATHS":false,"SUBinary":false,"busyBoxbinary":false,"dangerousProps":false,
// "potentiallyDangerousApp ":false,"rootCloakingApps":false,"rootManagementApp":false,"testkeys":false},"security_patch":"2022-06-01"},
// "freshnessIndicator":{"ts":1684394408340,"verifyCode":"94c759bf-417e-44d7-82f8-0f8dd2e4e01f"},
// "rngHealth":{"number":"b4f8246b0dcdb8f79adc76a1e4bd1588d610dcc75859465137fa43e521ea5f8c",
// "keyLen":32,"entropy":"780dc264ddf16ac9a2eec6c694ac54ef021a0e2c4e1fa236dd234099af4f2d28",
// "nonce":"8d0ec1c5bbf98486cd3fbfaec75b00eb","perStr":"9e915c31a070a81329f317a8dd896b85"},
// "playIntegrityToken":"eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2R0NNIn0.tFBagCyamgRx7bwkxIC7EB8-ReHTglnpFevrxXmVxqQE0g1OY0D-xg.oGpHiuoCqxbXnoyp.OIBppjJ15_TtAGZ2N0e9tKjPjqdJEXz8pvULzFxWGYTBOj6Wfl6fr07PRT8znkmAguSoHP6RkjTvH-GRTEuiVDG_CNrW5bRFwzBO5fB3x61R-12238oE7Qp1z20cTPaeRFb6kyxXBKQJ8wJa78Adb0h_oJWTuxIc2vp8dYsVbw0i1aNgbMXGHkyc3xw3cSSqHV2q41PpHCWT3by4A7Nz-aAHL_BhtffkuFZ7au05Utr1eAysTRnPWVm5BGhm8RLK8OqEYdaOmUcWR15iVVKFkmA4Ae7UA8Ghq6loIPj5BSEsTjEXBXTsiyTLWsffZvvh77AEKFS__af_b6dRc6mdvVy9gQB-P57Qh3_f7QaXT3LlYkfQSQ4z1tGR7p5I8N7OIfZPrajeI5doHvwM2jAXUOz6AIO192NfuAE-97B6VYpGJWkBH4FjwXx8bWEd7wDBIwNo9B2u6QnR7lOr0SPt1ykePBGxV7MJ0HTilwY23g92iZ_l7SylIZTsMiPH6QnNPWlS6mjDAeLldXEcbLLvAFccewJ86FmUUCrDcPXSsFIYq3GPeubColQQtbgxx8T7wnglIV1Bkv-XpF6Qimk7mnsvSU0NQsEnpFkFbSGZFoPe1sPbBDqv73OmPtDpo5Tnt4OXqdcLhvkipvHlp91NgRXES1kZw4ibP7wc3XlPoybtYqBrOmsniCi9BhCLg2KwdQRb6QlonCsR4gGH6eJEykl_CCxa5uVtc8SzksuDmepmC12s4Qo1qHGCPVA_uj1idXR7iGoVji83y0MqzFD0qNde0Hs-KLfgbs8fid3VIot1Pr5d95wT51Li4dAcLRQwqLb5JUUZ6FD_bENlx2yez_VU-m7RKXvqX5MVudvrOcAZnD_dFWSjAjzHFy2r2397GL8rG7H5A6olbtrEj7AR6K0AAmPAXRA7DpcWg6ttVCkNvBQVyIyNoJMewJpxB6CTCYhQjE_c_i7B3O5ynJjWUgsbgY_FgBeqLbMuzugBKmYy5lcsTzAsHU_js5pJisyGtnvEdjRngLtxJnrv-2RnrHFgUFUaFTH2ylrfdyYGoBZoetKNKnvWKwZdOmoC9pOszGMN-CeuTh7o9GvRNYlpMUZmjseumMGLqKeOyaJyuiQsoU-T-_7qlQyCgjMyJj3LFbIvyrAh3JkE7oBGXTDjfpP71AySFc9OVLkckQygCqCp4vMmyIrvA
// 4T66_xyRd-Rl9pXzhGw46mMmj4jl5kdhv9C.n9o4PSQRkG2Mc_cdZ3jpdQ"}